### ISSUE TITLE
Configuration for all account types

### ISSUE THREAD

**Issue by benpea** [Yvand/AzureCP#3] opened 2017-02-02 03:53 UTC
Hi, I am having trouble with getting the solution to work with all type of users within azure AD.

Currently we have the AzureCP configured to map claims/upn to property to query: mail.
This allows the following account types to login/resolve:
-Guest Users within a Federated Directory (B2B user with ADFS on their side)
-Guest User without a Federated Directory (B2B user without ADFS)
-AAD Security group roles
This configuration however **does not work** with:
-Local accounts created with an onmicrosoft.com address i.e someone@tenant.onmicrosoft.com

When configured as default (claims/upn mapped to query UPN):
Accounts that work:
-Local accounts created with an onmicrosoft.com address i.e someone@tenant.onmicrosoft.com
-Guest Users within a Federated Directory (B2B user with ADFS on their side)
Accounts that **don't work**:
-Guest User without a Federated Directory (B2B user without ADFS)

Can you confirm this is a limitation or is their a configuration change that can be made to have all account types work?

Regards
Ben.

**Comment by Yvand** [comment] 2017-02-08 12:05
Hello, I will test this configuration and come back to you ASAP, hopefully this week

**Comment by Yvand** [comment] 2017-02-08 15:02
AzureCP expects that you always use property UserPrincipalName for users, because AAD sets the main claim type (<i>http://schemas.xmlsoap.org/ws/2005/05/identity/claims/name</i>) with this property, and SAML token doesn't contain the email address.

Then in ACS or ADFS, you may transform this claim type in either <i>http://schemas.xmlsoap.org/ws/2005/05/identity/claims/upn</i> or <i>http://schemas.xmlsoap.org/ws/2005/05/identity/claims/emailaddress</i> but it's still the same AAD property (UserPrincipalName).

Below is from the SAML token that login.microsoftonline.com posted to the user upon successful authentication, the value matches the property UserPrincipalName (which is called "User name" in https://portal.azure.com):

```xml
<Attribute Name="http://schemas.xmlsoap.org/ws/2005/05/identity/claims/name">
<AttributeValue>AzureUser1@TENANT.onmicrosoft.com</AttributeValue>
</Attribute>
```

**Comment by benpea** [comment] 2017-02-10 07:00
Hi Yvand,


First of all, thanks for getting back to me, I appreciate it.


I think I didn't explain the issue I am facing correctly; We are using B2B user accounts as such the UPN for these account types are a bit strange in the back end "test.user_domain.com.au#EXT#@tenantname.onmicrosoft.com" the same format that is stored for MS accounts


as such with the Claims configuration set to "UPN -> UserPrincibleName" (below)

[cid:9a4b2c19-9fce-4e58-ade2-ed71797ca3f9]


what we are seeing is that while AzureCP can locate the users in the people pickers etc, the users claim added to SharePoint looks like:

 "i:0e.t|<claims provider name>|test.user_domain.com.au#EXT#@tenantname.onmicrosoft.com"

 and when the user logs in they are prompted with an access denied error within SharePoint, I suspect this is due to the for mentioned value stored in SP.



When we change the AzureCP configuration to:

[cid:ce82f021-19ae-4e88-ba12-2dabe3f05e87]


Users are still findable in the People pickers (well most - will get to that shortly)

and the user when added to sharepoint looks like:

 "i:0e.t|<claims provider name>|test.user@domain.com.au" as what normal users do with a normal UPN local accounts.

Issue is that when configured this way it works for B2B Guest accounts, but breaks accounts of type:  Local Account (onmicrosoft.com).

Any advice would be great!


-Ben




________________________________

**Comment by Yvand** [comment] 2017-02-21 16:02
Hello, I didn't configure this myself but I discussed this with a colleague who did and we discussed your scenario.
I'll come back to you later, hopefully this week, with more information for your scenario

**Comment by Yvand** [comment] 2017-03-16 13:06
Hi @benpea,
sorry for the late reply. I reproduced your issue, and you are correct:
- For B2B (guest) users: AAD does not issue claim http://schemas.xmlsoap.org/ws/2005/05/identity/claims/name that would contain userPrincipalName value (typically "yvand_external.com#EXT#@TENANT.onmicrosoft.com"), instead it issues claims http://schemas.xmlsoap.org/ws/2005/05/identity/claims/emailaddress with the actual email of the user.
- For normal (member) users: AAD issues claim http://schemas.xmlsoap.org/ws/2005/05/identity/claims/name that contains userPrincipalName value (typically "AzureUser1@TENANT.onmicrosoft.com"), and it does not issue email claim.

On the other hand, AzureCP always sets the identity permission with the userPrincipalName value, so indeed this doesn't work for B2B users since AAD does not send this attribute.
Are you using ACS or ADFS between SharePoint and AAD?

A possible solution that does not require any change on AzureCP is to configure ADFS to retrieve the userPrincipalName of the B2B users and issue it with the identity claim type set on SharePoint.
This solution cannot be done with ACS.
Does this sound like a possible solution for you?

**Comment by aboredman** [comment] 2017-04-03 19:46
I have a very similar use case and I would like to reproduce the config achieved by benpea but the comment from Feb 10th has no screenshot. Yvan or Ben, could you include them?

**Comment by benpea** [comment] 2017-04-04 01:11
Hi Yvand, 

Sorry i took a while to respond,

Your proposed solution via ADFS unfortunately defeats the purpose of the entire B2B model. B2B (Business to business) is designed to users can sign in using their own organisations credentials, so as such they will be authenticating against THIER OWN ADFS server, currently my client has 170+ business partners connecting via B2B, so you can understand we could not expect all 170 partners to modify their ADFS on their side.  Unfortunately only solution i can see, requires a change to AzureCP.

Is this something that you think would be possible?

Ben

**Comment by aboredman** [comment] 2017-04-04 19:52
Thanks to Ben I managed to reproduce his config where B2B guest accounts can be used. 

If it helps someone esle it can be done by adding those 2 rules in ACS Rule Group

![image](https://cloud.githubusercontent.com/assets/7316670/24675715/3bce5f64-194e-11e7-960a-b5f12cc65d8a.png)

![image](https://cloud.githubusercontent.com/assets/7316670/24675735/493e7f12-194e-11e7-8ea0-9f75d422fa48.png)

Then setting the following in AzureCP:

![image](https://cloud.githubusercontent.com/assets/7316670/24675782/70726de6-194e-11e7-8395-f733d05993d9.png)

Obviously this solution is not perfect as it will only work with Guest accounts from B2B and every other AzureAD accounts will stop working (see Benpea post). 

I don't know how feasible this is but it would be a great addition to support both Regular and Guest accounts to AzureCP.

**Comment by benpea** [comment] 2017-11-30 09:01
Ummm closed?

Its still an issue that I have to deal with almost daily, common man!

**Comment by Yvand** [comment] 2017-11-30 09:08
Hi @benpea 
sorry I should have given some justification:
This is an actual issue, but I closed it because I don't see any possible solution on AzureCP side.

I think this should be addressed on ADFS side: create custom rules on ADFS to change the claim type type of B2B accounts from http://schemas.xmlsoap.org/ws/2005/05/identity/claims/name to whatever the identity claim type is in SharePoint (e.g. http://schemas.xmlsoap.org/ws/2005/05/identity/claims/emailaddress).
What do you think?

**Comment by benpea** [comment] 2017-11-30 09:13
Hi Yvand, I would love to be able to discuss the issue with you, as this is an issue with b2b accounts and by definition environments outside of our control. 

For example we invite a user from company 'xyz' "user@xyz.com' to use our system. they are loggin in using their infrastructure, they may have ADFS installed in their environment but we can not re-configure that.  They may not, and just be using default o365 login's without ADFS even in the picture.

To me it seems like a relatively easy fix from the software side of things, as the workaround described above could be added as default behavior of the plug in no? (I know that's simplifying it somewhat).

I hope you understand this is an issue with external users where we have no control over their environment, as such "adding rules to ADFS" is never going to be a viable option.

**Comment by benpea** [comment] 2017-11-30 09:20
If it helps, a network trace of the login shows the communication flow as such:

User -> site -> azure ACS (accesscontrol.winsows.net) -> login.windows.net -> Either A) stays at login.windows.net or goes to users ADFS login page -> login.windows.net -> site.

So they do not pass through any environment we could make the rule you suggest.

**Comment by Yvand** [comment] 2017-12-11 14:47
Hi @benpea, sorry for the late reply.
I do understand the issue, and I was not suggesting that you fix the issue in the ADFS of your customers.

About your flow, I think it is like this because you use ACS, can you confirm this?
In this case yes, you are probably in a deadend.

But instead of ACS you could use ADFS of your organization. In this case, all SAML tokens of all users would go to ADFS and you could do some transformation to change the claim types when needed.
Does that make sense?

**Comment by Yvand** [comment] 2018-03-19 09:30
@benpea can you please confirm if [version 11](https://github.com/Yvand/AzureCP/releases/tag/v11) addressed your needs?

**Comment by benpea** [comment] 2018-08-10 09:03
Hi Yvand, Thanks for the update, I will inform the client of the update and see about getting this tested and will let you know, and you are correct we are using ACS (work coming up to migrate to ADFS as ACS is retiring). I will let you know how we go. Thanks!

**Closed** 2018-09-17 08:55 UTC
Labels: question
